WITH SOURCE AS (
    SELECT *
    FROM {{ source('olist_raw', 'RAW_OLIST_ORDER_PAYMENTS') }}
),

RENAMED AS (
    SELECT
        ORDER_ID
        ,PAYMENT_INSTALLMENTS
        ,PAYMENT_SEQUENTIAL
        ,PAYMENT_TYPE
        ,CAST(PAYMENT_VALUE AS NUMBER(10,2)) AS PAYMENT_VALUE
    FROM SOURCE
)

SELECT * FROM RENAMED