WITH SOURCE AS (
    SELECT 
        *
        , ROW_NUMBER() OVER (PARTITION BY REVIEW_ID ORDER BY REVIEW_CREATION_DATE DESC) AS RN
    FROM {{ source('olist_raw', 'RAW_OLIST_ORDER_REVIEWS') }}
),

DEDUPED AS (
    SELECT
        *
    FROM SOURCE
    WHERE RN = 1
)

SELECT * FROM DEDUPED