WITH SOURCE AS (
    SELECT *
    FROM {{ source('olist_raw', 'RAW_OLIST_DEALS') }}
),

RENAMED AS (
    SELECT
        MQL_ID
        ,SELLER_ID
        ,SDR_ID
        ,SR_ID
        ,CAST(WON_DATE AS timestamp_ntz) AS WON_DATE_TS
        ,BUSINESS_SEGMENT
        ,LEAD_TYPE
        ,LEAD_BEHAVIOUR_PROFILE
        ,HAS_COMPANY
        ,HAS_GTIN
        ,AVERAGE_STOCK
        ,BUSINESS_TYPE
        ,CAST(DECLARED_PRODUCT_CATALOG_SIZE AS NUMBER(10,2)) AS DECLARED_PRODUCT_CATALOG_SIZE
        ,CAST(DECLARED_MONTHLY_REVENUE AS NUMBER(10,2)) AS DECLARED_MONTHLY_REVENUE
    FROM SOURCE
)

SELECT * FROM RENAMED