WITH SOURCE AS (
    SELECT *
    FROM {{ source('olist_raw', 'RAW_OLIST_GEOLOCATION') }}
),

RENAMED AS (
    SELECT
        GEOLOCATION_ZIP_CODE_PREFIX
        ,GEOLOCATION_LAT
        ,GEOLOCATION_LNG
        ,GEOLOCATION_CITY
        ,GEOLOCATION_STATE
    FROM SOURCE
)

SELECT * FROM RENAMED