WITH SOURCE AS (
    SELECT *
    FROM {{ source('olist_raw', 'RAW_OLIST_ORDER_ITEMS') }}
),

RENAMED AS (
    SELECT
        ORDER_ID
        ,ORDER_ITEM_ID
        ,PRODUCT_ID
        ,SELLER_ID
        ,CAST(SHIPPING_LIMIT_DATE AS timestamp_ntz) AS SHIPPING_LIMIT_TS
        ,CAST(PRICE AS NUMBER(10,2)) AS PRICE
        ,CAST(FREIGHT_VALUE AS NUMBER(10,2)) AS FREIGHT_VALUE
    FROM SOURCE
)

SELECT * FROM RENAMED