WITH SOURCE AS (
    SELECT *
    FROM {{ source('olist_raw', 'RAW_OLIST_PRODUCTS') }}
),

RENAMED AS (
    SELECT
        PRODUCT_ID
        ,PRODUCT_CATEGORY_NAME
        ,PRODUCT_NAME_LENGTH
        ,PRODUCT_DESCRIPTION_LENGTH
        ,PRODUCT_PHOTOS_QTY
        ,PRODUCT_WEIGHT_G
        ,PRODUCT_LENGTH_CM
        ,PRODUCT_HEIGHT_CM
        ,PRODUCT_WIDTH_CM
    FROM SOURCE
)

SELECT * FROM RENAMED