WITH ORDERS AS (
    SELECT
        CUSTOMER_SK
        ,TO_DATE(ORDER_PURCHASE_TS) AS ORDER_DATE
        ,ORDER_REVENUE
    FROM {{ref('fct_orders')}}
),

BY_CUSTOMER_DAY AS (
    SELECT
        CUSTOMER_SK
        ,ORDER_DATE AS DATE
        ,COUNT(*) AS ORDERS_COUNT
        ,SUM(ORDER_REVENUE) AS REVENUE
    FROM ORDERS
    GROUP BY CUSTOMER_SK, ORDER_DATE
),
WITH_WINDOW_METRICS AS(
    SELECT
        CUSTOMER_SK
        ,DATE
        ,ORDERS_COUNT
        ,REVENUE

        -- command rank
        ,ROW_NUMBER() OVER (PARTITION BY CUSTOMER_SK ORDER BY DATE) AS ORDER_NUMBER_FOR_CUSTOMER

        -- cumulative order amount
        ,SUM(ORDERS_COUNT) OVER(PARTITION BY CUSTOMER_SK ORDER BY DATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CUMULATIVE_ORDERS_COUNT

        -- cumulative revenue
        ,SUM(REVENUE) OVER (PARTITION BY CUSTOMER_SK ORDER BY DATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CUMULATIVE_REVENUE
        
        -- first and lasst day of order
        ,FIRST_VALUE(DATE) OVER (PARTITION BY CUSTOMER_SK ORDER BY DATE) AS FIRST_ORDER_DATE_FOR_CUSTOMER
        ,LAST_VALUE(DATE) OVER (PARTITION BY CUSTOMER_SK ORDER BY DATE) AS LAST_ORDER_DATE_FOR_CUSTOMER
    FROM BY_CUSTOMER_DAY
),
FINAL AS (
    SELECT
        CUSTOMER_SK
        ,DATE
        ,DATE_TRUNC('month', DATE)::DATE AS DATE_MONTH
        ,ORDERS_COUNT
        ,REVENUE AS DAILY_REVENUE
        ,CUMULATIVE_ORDERS_COUNT
        ,CUMULATIVE_REVENUE

        ,CASE
            WHEN DATE = FIRST_ORDER_DATE_FOR_CUSTOMER THEN 1
            ELSE 0
        END AS IS_FIRST_ORDER_FOR_CUSTOMER
        ,CASE
            WHEN DATE = LAST_ORDER_DATE_FOR_CUSTOMER THEN 1
            ELSE 0
        END AS IS_LAST_ORDER_FOR_CUSTOMER
    FROM WITH_WINDOW_METRICS
)

SELECT * FROM FINAL