USE DATABASE ECOMMERCE_OLIST;
USE SCHEMA RAW;
USE WAREHOUSE WH_OLIST;

CREATE OR REPLACE FILE FORMAT RAW.CSV_OLIST_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY= '"'
    NULL_IF = ('', 'NULL');

-- Execute first time only
-- CREATE OR REPLACE STAGE RAW.STG_OLIST
--     FILE_FORMAT = RAW.CSV_OLIST_FORMAT;

COPY INTO RAW.RAW_OLIST_ORDERS
FROM '@"ECOMMERCE_OLIST"."RAW"."STG_OLIST"/olist_orders_dataset.csv'
FIlE_FORMAT = (FORMAT_NAME = RAW.CSV_OLIST_FORMAT);

COPY INTO RAW.RAW_OLIST_ORDER_ITEMS
FROM '@"ECOMMERCE_OLIST"."RAW"."STG_OLIST"/olist_order_items_dataset.csv'
FIlE_FORMAT = (FORMAT_NAME = RAW.CSV_OLIST_FORMAT);

COPY INTO RAW.RAW_OLIST_ORDER_PAYMENTS
FROM '@"ECOMMERCE_OLIST"."RAW"."STG_OLIST"/olist_order_payments_dataset.csv'
FIlE_FORMAT = (FORMAT_NAME = RAW.CSV_OLIST_FORMAT);

COPY INTO RAW.RAW_OLIST_ORDER_REVIEWS
FROM '@"ECOMMERCE_OLIST"."RAW"."STG_OLIST"/olist_order_reviews_dataset.csv'
FIlE_FORMAT = (FORMAT_NAME = RAW.CSV_OLIST_FORMAT);

COPY INTO RAW.RAW_OLIST_CUSTOMERS
FROM '@"ECOMMERCE_OLIST"."RAW"."STG_OLIST"/olist_customers_dataset.csv'
FIlE_FORMAT = (FORMAT_NAME = RAW.CSV_OLIST_FORMAT);

COPY INTO RAW.RAW_OLIST_PRODUCTS
FROM '@"ECOMMERCE_OLIST"."RAW"."STG_OLIST"/olist_products_dataset.csv'
FIlE_FORMAT = (FORMAT_NAME = RAW.CSV_OLIST_FORMAT);

COPY INTO RAW.RAW_OLIST_SELLERS
FROM '@"ECOMMERCE_OLIST"."RAW"."STG_OLIST"/olist_sellers_dataset.csv'
FIlE_FORMAT = (FORMAT_NAME = RAW.CSV_OLIST_FORMAT);

COPY INTO RAW.RAW_OLIST_GEOLOCATION
FROM '@"ECOMMERCE_OLIST"."RAW"."STG_OLIST"/olist_geolocation_dataset.csv'
FIlE_FORMAT = (FORMAT_NAME = RAW.CSV_OLIST_FORMAT);

COPY INTO RAW.RAW_PRODUCT_CATEGORY_NAME_TRANSLATION
FROM '@"ECOMMERCE_OLIST"."RAW"."STG_OLIST"/product_category_name_translation.csv'
FIlE_FORMAT = (FORMAT_NAME = RAW.CSV_OLIST_FORMAT);

COPY INTO RAW.RAW_OLIST_LEADS
FROM '@"ECOMMERCE_OLIST"."RAW"."STG_OLIST"/olist_marketing_qualified_leads_dataset.csv'
FIlE_FORMAT = (FORMAT_NAME = RAW.CSV_OLIST_FORMAT);

COPY INTO RAW.RAW_OLIST_DEALS
FROM '@"ECOMMERCE_OLIST"."RAW"."STG_OLIST"/olist_closed_deals_dataset.csv'
FIlE_FORMAT = (FORMAT_NAME = RAW.CSV_OLIST_FORMAT);