USE ROLE ACCOUNTADMIN;

-- 1) BASE
CREATE OR REPLACE DATABASE ECOMMERCE_OLIST;

-- 2) SCHEMAS
CREATE OR REPLACE SCHEMA ECOMMERCE_OLIST.RAW;
CREATE OR REPLACE SCHEMA ECOMMERCE_OLIST.STAGING;
CREATE OR REPLACE SCHEMA ECOMMERCE_OLIST.MARTS;

-- 3) WAREHOUSE
CREATE OR REPLACE WAREHOUSE WH_OLIST
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

CREATE OR REPLACE ROLE DBT_ROLE;

SHOW GRANTS ON WAREHOUSE WH_OLIST;
GRANT USAGE ON WAREHOUSE WH_OLIST TO ROLE DBT_ROLE;
GRANT ROLE DBT_ROLE TO USER jpvinh;
GRANT ALL ON DATABASE ECOMMERCE_OLIST TO ROLE DBT_ROLE;
GRANT ALL ON SCHEMA ECOMMERCE_OLIST.RAW TO ROLE DBT_ROLE;
GRANT ALL ON SCHEMA ECOMMERCE_OLIST.STAGING TO ROLE DBT_ROLE;
GRANT ALL ON SCHEMA ECOMMERCE_OLIST.MARTS TO ROLE DBT_ROLE;

USE ROLE DBT_ROLE;

SHOW SCHEMAS